### PR TITLE
fix: should use a timezoned date

### PR DESCRIPTION
**Pull request by elvishp2006**
* https://developer.wordpress.org/block-editor/reference-guides/packages/packages-date/#isinthefuture
Captura de Tela 2022-06-23 às 14 24 01

### CODE REVIEW

**Review by elvishp2006 — COMMENTED** [review]
The status is being pined on future bacause I'm using a -3:00h timezone

**Comment by kassyn** [comment]
I have same problem!

**Comment by imath** [comment]
Looks good, thanks a lot for your contribution @elvishp2006 and sorry it took me so long to merge it.

**Comment by elvishp2006** [comment]
Thanks @imath :)

**Pull request merged**
